#this is a test file to test things.
bake:
  general:
    #version of the configuration, leave it be
    configVersion: 5
    #amounts of 'slots' used, the more, the more items you can award, but there might be lag.
    slots: 5
    #should only contributors be awarded. (non-contributors will not recieve anything)
    remember: true
    #should the contributors list be removed when the project is finished (it will not be saved anywhere, so when the server restarts, it is gone either way)
    deleteRemembered: true
    #should nothing be overridden (except bake.save.*)
    noMeddle: false
    #leave it be, setting it to false will break almost everything
    cnfgStore: true
    #Should enchants get automatically converted ("might" fix bugs connected to enchants, but can cause longer starting times or even cause them.)
    doEnchantConvert: true
    #should a broadcast be done when the day's record is broken?
    doRecordSurpassBroadcast: true
    #should the leaderboard be used?
    useLeaderboard: true
    #should the player we rewarded when they rejoin after they contributed and the project was finished in their absence?
    rewardLater: true
  #amount of required wheat
  wheat_Required: 1000
  metrics:
    #set this to false if you don't want bake to contact https://geolykt.de/src/bake/bakeMetrics.php
    opt-out: false
  award:
    #amount of vault money that should be given to each participant on completion.
    money: 1000
    #maximum amount of things that can be rewarded, so if it is set to 1 only 1 itemstack will be given out, however it can also award less.
    maximum: 10
    #the slot talked before will come handy here, please mind that it starts with 0 and ends with n - 1
    '0':
      'type': DIAMOND
      'chance': 0.5
      'count': 3
      'lore': §dThank you for participating!
      'display_name': §9A DIAMOND
      'enchantment': UNBREAKING@5
    '1':
      'type': CAKE
      'chance': 1
      'count': 1
      'lore': §dThank you for participating!| Here! Have a cake!
      'display_name': §cYUMMY!
      'enchantment': UNBREAKING@5|MENDING@1
    '2':
      'type': NETHER_STAR
      'chance': 0.05
      'count': 1
      'lore': §dThank you for participating!
      'display_name': '§eSHINY!'
      'enchantment': ''
    '3':
      'type': GOLD_INGOT
      'chance': 0.1
      'count': 16
      'lore': §dThank you for participating!
      'display_name': ''
      'enchantment': ''
    '4':
      'type': COAL
      'chance': 0.8
      'count': 16
      'lore': §dThank you for participating!
      'display_name': ''
      'enchantment': ''
  chat:
    recordSurpassBroadcast: §6The previous record of %RECORD% on the %RECORDDATE%
      was broken by the new record of %TODAY%!
    progress2: "§b=========== Running Bake %VERSION%  ============ \n §bThe Bake Progress\
      \ is: %INTPROG% of %INTMAX% \n §bSo we are %PERCENT% % done! Keep up! \n§b ======================================="
    bakestats: "§b========================================\n The bake project was\
      \ completed %TIMES% times in total, the last time on %LAST%.§b \n The most projects\
      \ were completed on %RECORDDATE% with %RECORD% times. \n§bA total of §c%PARTICIPANTS%§\
      b participated in the recent project.\n§b========================================"
    contr2: '%INTPROG% was added to the project! Thanks!'
    global:
      contr2: §6%PLAYER% has contributed %INTPROG% to the bake projects! We are now
        a bit closer to the rewards!
    finish2: §l§bThe bake project is finished! Everyone gets the rewards!
    leaderboard:
      'pre': "§b===== Bake best contributors ====="
      'mid': "%d.: %-31s :§4 %s"
      'post': "§b==============================="
      'unavail': "§4Bake leaderboards are not supported right now right here. Try again later."
    gBakeRefresh: "§4[BAKE] §6 Other servers have contributed %INTPROG%!"
    welcomeBack: "§6[BAKE] During your absence the Bake project has been finished! As a contributor, you get some rewards!"
  #don't mess with these values, well you can but it doesn't give you much
  save:
    times: 0
    last: '1970-01-01T00:00:00Z'
    recordtime: '1970-01-01T00:00:00Z'
    record: 0
    today: 0
    participants: 0
    participantsToday: 0
  gbake:
    #should the server compete on a international effort (requires HTTP access to the pointed update sites)
    enable: false
    update_server: 'http://src.geolykt.de/bake/globalbakeServer.php'
    update_client: 'http://src.geolykt.de/bake/gbakeRefresh.php'
    interval: 1000