#this is a test file to test things.
bake:
  general:
    #version of the configuration, leave it be
    configVersion: 7
    #amounts of 'slots' used, the more, the more items you can award, but there might be lag.
    slots: 5
    #should only contributors be awarded. (non-contributors will not recieve anything)
    remember: true
    #should the contributors list be removed when the project is finished (it will not be saved anywhere, so when the server restarts, it is gone either way)
    deleteRemembered: true
    #should nothing be overridden (including files like quests.yml but excluding savedata.yml)
    noMeddle: false
    #should a broadcast be done when the day's record is broken?
    doRecordSurpassBroadcast: true
    #should the leaderboard be used?
    useLeaderboard: true
    #should the player we rewarded when they rejoin after they contributed and the project was finished in their absence?
    rewardLater: true
    #whether vault should be used
    useVault: true
  metrics:
    #set this to false if you don't want bake to contact https://geolykt.de/src/bake/bakeMetrics.php
    opt-out: false
  chat:
    recordSurpassBroadcast: '§6[BAKE] The previous record of %RECORD% on the %RECORDDATE%
      was broken by the new record of %TODAY%!'
    #used in the /bake message
    progress2: "§b%TOOLTIP%\n §r %PERCENT% % done! (%INTPROG% / %INTMAX%)"
    #used in the /bakestats message
    bakestats: "Completions: %TIMES% \n Record: %RECORD% at %RECORDDATE% \n Last finished: %LAST% \n %PARTICIPANTS% Have contributed."
    contr2: '%INTPROG% was added to the project! Thanks!'
    global:
      contr2: '§6[BAKE]§r%PLAYER%§r§6 has contributed %INTPROG% to the bake projects! We are now a bit closer to the rewards!'
      #TODO: cooldown perhaps?
    finish2: §l§bThe bake project is finished! Everyone gets the rewards!
    leaderboard:
      'pre': "§b===== Bake best contributors ====="
      #TODO: maybe find a better way to make this a thing. This is a terrible way of doing it as it's in plaintext
      'mid': "%d.: %-31s :§4 %s"
      'post': "§b==============================="
      'unavail': "§4Bake leaderboards are not supported right now right here. Try again later."
    welcomeBack: "§6[BAKE] During your absence the Bake project has been finished! As a contributor, you get some rewards!"