name: bake
main: de.geolykt.bake.Bake
version: 1.9.1
author: Geolykt
api-version: 1.14
softdepend: [Vault] #Vault for money stuff
website: https://github.com/Geolykt/bake
commands:
  bake:
    description: Shows the progress of the bake and how much you need to contribute
    usage: "Usage: /bake"
    permission: bake.command.bake
    permission-message: You have insufficent permissions, you need bake.command.bake for that command, contact a server administrator if you belive that this is an error
  contribute:
    description: Contribute some wheat to the bake project
    usage: "Usage: /contribute [number]"
    permission: bake.command.contribute
    permission-message: You have insufficent permissions, you need bake.command.contribute for that command, contact a server administrator if you belive that this is an error
  bakestats:
    description: has the intended use for statistics surrounding the bake project
    usage: "Usage: /bakestats"
    permission: bake.command.stats
    permission-message: You have insufficent permissions, you need bake.command.stats for that command, contact a server administrator if you belive that this is an error
  baketop:
    description: Lists the best contributors
    usage: "Usage: /baketop"
    permission: bake.command.top
    permission-message: You have insufficent permissions, you need bake.command.top for that command, contact a server administrator if you belive that this is an error
permissions:
  bake.command.bake:
    description: allows the /bake command
    default: true
  bake.command.admin:
    description: allows the /bake admin subcommand or the /bake stop subcommand
    default: op
  bake.command.contribute:
    description: allows the /contribute command
    default: true
  bake.command.stats:
    description: allows the /bakestats command
    default: true
  bake.command.top:
    description: allows the /baketop command
    default: true